
services:
  app:
    build: .
    expose:
      - "8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - webapp-network
    restart: unless-stopped

  db:
    image: postgres:alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      #- postgres_data:/var/lib/postgresql/data
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - webapp-network
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app/static:/var/www/static
    depends_on:
      - app
    networks:
      - webapp-network
    restart: unless-stopped

#volumes:
#  postgres_data:

networks:
  webapp-network:
    driver: bridge
