"""initial migration

Revision ID: 6b3ba3dc0a57
Revises: 
Create Date: 2025-08-21 09:06:59.850719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b3ba3dc0a57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_responses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('banner', sa.String(length=512), nullable=True),
    sa.Column('http_response', sa.String(length=8192), nullable=True),
    sa.Column('headers', sa.String(length=4096), nullable=True),
    sa.Column('certificate', sa.String(length=8192), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('icon_hash', sa.String(length=32), nullable=True),
    sa.Column('scan_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_responses_id'), 'host_responses', ['id'], unique=False)
    op.create_table('network_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('network', postgresql.CIDR(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('last_assigned', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_blocks_id'), 'network_blocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_blocks_id'), table_name='network_blocks')
    op.drop_table('network_blocks')
    op.drop_index(op.f('ix_host_responses_id'), table_name='host_responses')
    op.drop_table('host_responses')
    # ### end Alembic commands ###
